### ISSUE TITLE
Something about bitmap

### ISSUE THREAD

**Issue by wangxf1030** [aranyia/WhoIsThis#1]
Hi,

I am working on a project which can detect Android application's anti-pattern. I found that in your project, in the class ContactAPI.java
 you use BitmapFactory.decodeResource to get Bitmap. Actually, you can try to resize the bitmap images so that it waste less memory, which is also recommended by the Android documentation:  http://developer.android.com/training/displaying-bitmaps/load-bitmap.html 
I hope this can help you a little bit, and I really want to hear your feedback:)

**Comment by aranyia** [comment]
Hello,

This project is not in active development currently, it's actually a few years old. Although based on your suggestion, I might look into it to learn more about bitmap handling in Android, or just for fun if nothing else.
It's unlikely that contact photos would be particularly large however, but you are right, it probably can be optimized at that point.
Your project sounds quite cool though. And apparently it works. :)

**Comment by wangxf1030** [comment]
Thanks very much and good luck :)
